from setuptools import setup, Extension
setup(
    name='pysendint', 
    version='1.0', 
    ext_modules = [Extension('pysendint', 
                             ['__wrappers.c',
                              'pysendint.c', 'sendIntegration.c', 'sendSync.c',
                              'chunkPlot_clnt.c', 'chunkPlot_xdr.c',
                              'dataCatcher_clnt.c', 'dataCatcher_xdr.c',
                              '/global/functions/getAntennaList.c',
                              '/global/functions/defaultingEnabled.c',
                              ],
                             extra_compile_args=['-fno-builtin-printf',
                                                 '-fno-builtin-fprintf',
                                                 '-fno-builtin-perror',
                                                 ],
                             extra_link_args=['-Wl,-wrap,printf',
                                              '-Wl,-wrap,fprintf',
                                              '-Wl,-wrap,perror',
                                              ],
                             )])
