SWARM_ROACH2_IP = 'roach2-%02d'

SWARM_MAPPING = '/global/configFiles/swarmMapping'
SWARM_MAPPING_COMMENT = '#'
SWARM_MAPPING_COLUMNS = 5
SWARM_MAPPING_INPUTS = (0, 1)
SWARM_MAPPING_CHUNKS = (0, 1)
SWARM_MAPPING_POLS = (0, 1)

SWARM_CLK_RATE = 143e6
SWARM_CHANNELS = 2**14
SWARM_SYNC_TIMEOUT = 60
SWARM_WSTEPS_PER_WCYCLE = 64
SWARM_CLOCKS_PER_WSTEP = 11 * 128 * 2048
SWARM_WCYCLE_CLOCKS = SWARM_WSTEPS_PER_WCYCLE * SWARM_CLOCKS_PER_WSTEP
SWARM_WALSH_TIME = SWARM_WCYCLE_CLOCKS / SWARM_CLK_RATE

SWARM_ALL_FID = range(8)
SWARM_ALL_CORE = range(4)
SWARM_SHIFT_SCHEDULE = 0x55505550
SWARM_FENGINE_CTRL = 'fengine_ctrl'
SWARM_CGAIN_GAIN = 'cgain_gain_%d'
SWARM_XENG_CTRL = 'xeng_ctrl'
SWARM_XENG_TVG = 'xengine_xeng_tvg_data%d'
SWARM_VISIBS_CORE = 'visibs_gbe0'
SWARM_VISIBS_DELAY_CTRL = 'visibs_delay_ctrl'
SWARM_VISIBS_TENGBE_CTRL = 'visibs_tengbe_ctrl'
SWARM_VISIBS_SENDTO_IP = 'visibs_gbe0_sendto_ip'
SWARM_VISIBS_SENDTO_PORT = 'visibs_gbe0_sendto_port'
SWARM_SOURCE_SEED = 'source_seed_%d'
SWARM_SOURCE_CTRL = 'source_ctrl'
SWARM_SCOPE_CTRL = 'scope_ctrl'
SWARM_NETWORK_IPBASE = 'network_ipbase'
SWARM_NETWORK_CORE = 'network_eth_%d_core'
SWARM_NETWORK_CTRL = 'network_ctrl'
SWARM_NETWORK_FID = 'network_fid'
SWARM_NETWORK_FIDS_EXPECTED = 'network_fids_expected'
SWARM_REG_FMT = '>I'

SWARM_SYNC_ARM_CMD = 'sma-walsh-arm'

SWARM_XENG_PARALLEL_CHAN = 8
SWARM_XENG_SIDEBANDS = ('LSB', 'USB')
SWARM_XENG_TOTAL = SWARM_XENG_PARALLEL_CHAN * len(SWARM_ALL_FID)

SWARM_VISIBS_N_PKTS = 512
SWARM_VISIBS_CHANNELS = 2048
SWARM_VISIBS_BASELINES = 128
SWARM_VISIBS_HEADER_SIZE = 8
SWARM_VISIBS_HEADER_FMT = '>II'
SWARM_VISIBS_PKT_SIZE = 1025 * 8
SWARM_VISIBS_SIDEBANDS = len(SWARM_XENG_SIDEBANDS)
SWARM_VISIBS_ACC_SIZE = SWARM_VISIBS_CHANNELS * SWARM_VISIBS_BASELINES * SWARM_VISIBS_SIDEBANDS * 2
